### ISSUE TITLE
ArUco-MarkerMapper/src/markermapper.cpp:18:10: fatal error: multicropdetect.h: No such file or directory

### ISSUE THREAD

**Issue by rahulsharma11** [elliotwoods/ArUco-MarkerMapper#1]
Hi, While building this project i am having error for 
"ArUco-MarkerMapper/src/markermapper.cpp:18:10: fatal error: multicropdetect.h: No such file or directory".
Any suggestions?
Thanks.

**Comment by elliotwoods** [comment]
Which build tool are you using?
I've only used this project with Visual Studio.
If you're in Visual Studio, then just make sure to add all the header folders into your include search path

**Comment by rahulsharma11** [comment]
I am using Linux,
And the commands to build that are described-
cd path; mkdir build;cd build;cmake ..;make ;
So i am getting error in make.

Also tried to google the perticular header but no success.

**Comment by elliotwoods** [comment]
hmm.. i can't find that file anywhere
maybe just try removing that line from the cpp?

**Comment by rahulsharma11** [comment]
I tried that too.
That's throwing error with some functions that are defined in that file.

**Comment by elliotwoods** [comment]
hmm - and is there a particular reason that you want to use my branch rather than the upstream branch? ah perhaps because it's on sourceforge not github?

here's a direct copy to my working build folder:
https://www.dropbox.com/sh/9ntkejwc21spdvk/AAAY_CBLK8dUFSWDbd1kQ93-a?dl=0 

and to the most recent version online (mine is a modified version of this):
https://sourceforge.net/projects/markermapper/

**Comment by rahulsharma11** [comment]
Thanks.
